//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ID { get; set; }
        public int StaffID { get; set; }
        public int ClientID { get; set; }
        public int ShipID { get; set; }
        public string Status { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Ship Ship { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
